# Site name
site_name: MS Fabric Labs
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - "VM Logon Instructions": run-inside-vm.md

  - "Microsoft Fabric":

    - "Fabric Warmup":
      - fabric-warmup/index.md
      - Summary: fabric-warmup/summary.md

    - "Lakehouse":
      - lakehouse/index.md
      - Summary: lakehouse/summary.md

    - "Medallion Architecture":
      - medallion-lakehouse/index.md
      - Summary: medallion-lakehouse/summary.md

    - "Ingest Pipeline":
      - ingest-pipeline/index.md
      - Summary: ingest-pipeline/summary.md

    - "Dataflows (Gen2)":
      - dataflows-gen2/index.md
      - Summary: dataflows-gen2/summary.md

    - "Analyse data in a Data Warehouse":
      - data-warehouse/index.md
      - Summary: data-warehouse/summary.md

    - "Monitor a Data Warehouse":
      - monitor-data-warehouse/index.md
      - Summary: monitor-data-warehouse/summary.md

    - "Real-time Intelligence":
      - real-time-intelligence/index.md
      - Summary: real-time-intelligence/summary.md

    - "Real-time Eventstream":
      - real-time-analytics-eventstream/index.md
      - Summary: real-time-analytics-eventstream/summary.md

    - "Data Activator":
      - data-activator/index.md
      - Summary: data-activator/summary.md

    - "Monitor Hub":
      - monitor-hub/index.md
      - Summary: monitor-hub/summary.md

    - "Secure Data Access":
      - secure-data-access/index.md
      - Summary: secure-data-access/summary.md

    - "Work with SQL Database":
      - work-with-database/index.md
      - Summary: work-with-database/summary.md

    - "Deployment Pipelines":
      - implement-cicd/index.md
      - Summary: implement-cicd/summary.md

not_in_nav: |
  index.md
  run-locally.md
  clean-up.md
  medallion-lakehouse/instructions-full.md
  mongo-db.md

# Theme
theme:
  name: material
  palette:
    primary: black
    accent: green
  features:
    - toc.integrate
    - content.code.copy
    - navigation.indexes   # makes section titles link to their index.md
  icon:
    logo: material/database
  static_templates:
    - 404.html

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: false
      toc_depth: 2

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde

plugins:
  - search
  - glightbox

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
